// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr3MB1QJWS2y3PasF-Fc-flLs388k9wYU',
    appId: '1:977584641309:web:169ee3d17d71254762bdf4',
    messagingSenderId: '977584641309',
    projectId: 'charla-vertex',
    authDomain: 'charla-vertex.firebaseapp.com',
    storageBucket: 'charla-vertex.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_pMVn5fQUOBFqZtRIj7fi975d1fv-JM',
    appId: '1:977584641309:android:aa8972504e4b1f8562bdf4',
    messagingSenderId: '977584641309',
    projectId: 'charla-vertex',
    storageBucket: 'charla-vertex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAexyiYiNt_RtrHT2aFwse2xysJSuNMPkk',
    appId: '1:977584641309:ios:bed66461bb843d5f62bdf4',
    messagingSenderId: '977584641309',
    projectId: 'charla-vertex',
    storageBucket: 'charla-vertex.appspot.com',
    iosBundleId: 'com.example.charlaVertexGemini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr3MB1QJWS2y3PasF-Fc-flLs388k9wYU',
    appId: '1:977584641309:web:15b53f4c1f30945662bdf4',
    messagingSenderId: '977584641309',
    projectId: 'charla-vertex',
    authDomain: 'charla-vertex.firebaseapp.com',
    storageBucket: 'charla-vertex.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAexyiYiNt_RtrHT2aFwse2xysJSuNMPkk',
    appId: '1:977584641309:ios:bed66461bb843d5f62bdf4',
    messagingSenderId: '977584641309',
    projectId: 'charla-vertex',
    storageBucket: 'charla-vertex.appspot.com',
    iosBundleId: 'com.example.charlaVertexGemini',
  );

}